### ISSUE TITLE
lose project_1_wrapper.v and xdc files

### ISSUE THREAD

**Issue by wangguoqing129** [bluetiger9/XilinxVideoDesigns#1]
Hello, can you provide these three files for zcu104-hdmi-in-out-vcu.tcl?

"/home/bluetiger/Dev/Xilinx/petalinux-ZCU104-custom/zcu104-vcu/hardware/xilinx-zcu104-2020.1/xilinx-zcu104-2020.1.srcs/sources_1/bd/project_1/hdl/project_1_wrapper.v"
"/home/bluetiger/Dev/Xilinx/petalinux-ZCU104-custom/zcu104-vcu/hardware/xilinx-zcu104-2020.1/xilinx-zcu104-2020.1.srcs/constrs_1/imports/xdc/zcu104_vcu_uc2_pll.xdc"
"/home/bluetiger/Dev/Xilinx/petalinux-ZCU104-custom/zcu104-vcu/hardware/xilinx-zcu104-2020.1/xilinx-zcu104-2020.1.srcs/constrs_1/imports/xdc/default.xdc"
#

I run zcu104-hdmi-in-out-vcu.tcl in vivado2020.1 windows10, but meet lose files error. Thank you!

My email : wangpo129@gmail.com

![Screenshot 2024-05-09 165605](https://github.com/bluetiger9/XilinxVideoDesigns/assets/155594945/459c582a-8127-4cd8-a8ac-bf4c58facbcc)

**Comment by bluetiger9** [comment]
Hi @wangguoqing129! :slightly_smiling_face:

I have not worked with Xilinx products for a while, but found the files you mentioned in some random backup of the project: [default.xdc.txt](https://github.com/bluetiger9/XilinxVideoDesigns/files/15282424/default.xdc.txt) / [project_1_wrapper.v.txt](https://github.com/bluetiger9/XilinxVideoDesigns/files/15282425/project_1_wrapper.v.txt) / [zcu104_vcu_uc2_pll.xdc.txt](https://github.com/bluetiger9/XilinxVideoDesigns/files/15282426/zcu104_vcu_uc2_pll.xdc.txt)

Just be aware that I've no idea which version of these files are, of if they are even the correct ones.

If you are interested check out my project on Hackster.io:
https://www.hackster.io/bluetiger9/rapid-prototyping-with-gstreamer-vitis-ai-and-deeplib-50a397

I describe there in detail what I did in the Xilinx project, so you could follow it if you want.

Thanks,
Attila
